let tempeature = 20;

if (tempeature >= 20) {
    console.log("high temperature");
} else {
    console.log("cool weather");
}

var marks = (10, 20, 30, 40);

studentdetails= {   

 telugu : 10,
 english : 20,
 mathes :30,
 science : 40,
 "totalmarks":100,
 "studentName": "sudheer",
 "fatherName" : "ramakrishna",
}
console.log("marks---", marks);
console.log("studentdetails---", studentdetails);

var age = 45;
    person = {
    category: "software",
    mobilenumber: 9160043029
};

console.log("age---", age);
console.log("category---", person.category);
console.log("mobilenumber---", person.mobilenumber);


